name: Test and Format

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  prettier:
    name: Run black
    runs-on: ubuntu-latest
    steps:
      - name: Setup for black
        uses: actions/checkout@v3
      
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: python -m pip install --upgrade pip && python -m pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Format files
        run: pipenv run black

      - name: Commit changes
        uses: mikeal/publish-to-github-action@master
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: "dev"

  tests:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Setup for tests
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: python -m pip install --upgrade pip && python -m pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run tests
        run: pipenv run test

      - name: Remove .gitignore from coverage report
        run: rm coverage_report/.gitignore

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: coverage_report